README.md, web/package.json, web/src/render/App.vue, web/src/render/api/base.js, web/src/render/api/survey.js, web/src/render/pages/index.vue, web/src/render/store/actions.js, web/src/render/store/mutations.js, web/src/render/store/state.js, web/src/render/utils/encrypt.js
=> [Feature]: 传输加密前端实现

server/src/apps/surveyManage/service/surveyService.ts
=> [Feature]: 新增修改中的状态

web/src/management/pages/list/components/baseList.vue, web/src/management/pages/list/components/state.vue, web/src/management/pages/list/config/index.js
=> [Feature]: 问卷列表增加状态和更新新时间列

server/package.json, server/scripts/run-local.ts
=> [Feature]: 支持windows启动服务端

docker-compose.yaml
修改xiaojuSurveyMongoUrl默认值 && 增加网络配置
=> [chore]: docker-compose优化，修改xiaojuSurveyMongoUrl默认值 && 增加网络配置

server/scripts/run-local.ts
=> [Fix]: 修改windows启动兼容问题

server/package.json, server/src/apps/user/index.ts, server/src/apps/user/service/captchaService.ts, server/src/apps/user/utils/index.ts, web/src/management/api/captcha.js, web/src/management/api/user.js, web/src/management/pages/login/index.vue, web/src/management/store/actions.js, web/src/management/store/edit/actions.js, web/src/render/components/header.vue, web/src/render/components/logo.vue, web/src/render/components/mainRenderer.vue
1、编辑端登陆功能新增图片验证码
2、优化build命令，部署无需再执行copy命令
=> [Feature]: 登陆新增图片验证码功能

Dockerfile, server/src/router.ts, web/src/management/pages/login/index.vue, web/vue.config.js
=> [Fix]: 修复部署的问题

Dockerfile, server/package.json, server/src/apps/security/config/index.ts, server/src/apps/security/dataSecurityPlugins/aesPlugin/index.ts, server/src/apps/security/dataSecurityPlugins/aesPlugin/util.ts, server/src/apps/security/dataSecurityPlugins/interface.ts, server/src/apps/security/index.ts, server/src/apps/security/utils/index.ts, server/src/apps/surveyManage/service/surveyService.ts, server/src/apps/surveyManage/utils/index.ts, server/src/apps/surveyPublish/config/index.ts, server/src/apps/surveyPublish/service/surveySubmitService.ts, server/src/apps/surveyPublish/utils/checkSign.ts, server/src/apps/user/config/index.ts, server/src/apps/user/index.ts, server/src/router.ts, web/src/management/api/base.js, web/src/management/pages/analysis/index.vue
回收数据入库前对敏感数据进行加密
数据表格脱敏优化，脱敏更精细化，只针对敏感数据进行脱敏
=> [Feature]: 新增回收数据存储加密

server/src/apps/surveyManage/index.ts, server/src/apps/surveyManage/service/surveyService.ts
=> [Feature]: 新增复制接口

web/src/management/api/survey.js, web/src/management/pages/list/components/baseList.vue, web/src/management/pages/list/components/modify.vue, web/src/management/pages/list/components/toolBar.vue, web/src/management/utils/constant.js
=> [Feature]: 列表页新增复制功能

server/src/apps/surveyManage/index.ts, server/src/apps/surveyManage/service/surveyService.ts
=> [Feature]: 问卷列表接口新增搜索功能

web/src/management/api/survey.js, web/src/management/pages/list/components/baseList.vue, web/src/management/pages/list/components/textSearch.vue, web/src/management/pages/list/config/index.js, web/src/management/pages/list/index.vue
1. 新增搜索框组件
2. 列表页引用搜索框组件
3. 调整列表接口传参
=> [Feature]: 列表页新增搜索功能

README.md, server/package.json, server/src/apps/surveyManage/index.ts, server/src/apps/user/index.ts, server/src/apps/user/service/captchaService.ts, server/src/apps/user/utils/index.ts, server/src/index.ts, web/src/management/pages/list/components/baseList.vue, web/src/management/pages/list/components/textButton.vue, web/src/management/pages/list/components/textSelect.vue, web/src/management/pages/list/config/index.js
=> [Feature]: 问卷列表新增类型和状态筛选

server/src/apps/surveyManage/index.ts, server/src/apps/surveyManage/service/surveyService.ts
=> [Fix]: 修改列表接口排序功能的bug

web/src/materials/questions/components/Options/OptionEditBar.vue, web/src/materials/questions/widgets/EditOptions.jsx
修复评分组件点击高级设置修改后，再次点击高级设置看不到修改内容的问题。
=> fix:修复评分组件高级设置显示异常

web/src/render/components/progressBar.vue
=> [fix]:修复h5模式下没填完进度条已满问题

server/src/modules/survey/controllers/survey.controller.ts
=> [Fix]: 创建问卷remark允许空

server/src/modules/survey/controllers/survey.controller.ts
修改创建问卷接口remark字段允许空字符串
修改参数错误抛出httpexception
=> [fix]: 修改创建问卷错误处理

server/src/modules/survey/controllers/surveyMeta.controller.ts
修改更新问卷基础信息的接口允许remark字段为空
修改更新问卷报错的提示语
=> [Fix]: 修改更新问卷基础信息的接口允许remark字段为空

server/src/modules/auth/controllers/auth.controller.ts
=> [Fix]: 解决冲突

web/src/management/styles/icon.scss
=> chore: 更新iconfont

server/src/modules/survey/utils/index.ts
1. getListHeadByDataList函数里面的兼容nps题型
=> fix: getListHeadByDataList函数里面兼容radio-nps

server/src/modules/message/controllers/messagePushingTask.controller.ts, server/src/modules/message/dto/createMessagePushingTask.dto.ts, server/src/modules/message/dto/queryMessagePushingTaskList.dto.ts
=> [Feature]: 消息模块新增参数校验

server/src/modules/file/__test/alioss.handler.spec.ts
=> [Fix]: 修改alioss.handler中单测文件的报错

web/src/materials/questions/widgets/EditOptions/Options/OptionEditBar.vue
=> fix:解决ts报错

web/src/management/pages/edit/pages/setting/index.vue
=> fix: 修复文件缺少后缀

web/src/management/components/EmptyIndex.vue, web/src/management/components/LeftMenu.vue, web/src/management/components/LogoIcon.vue
下列组件, 调整成 Vue3 组合式 API 写法
```bash
management                                        
│   ├── components
│   │   ├── EmptyIndex.vue
│   │   ├── LeftMenu.vue
│   │   └── LogoIcon.vue
```
=> refactor: 重构 management/components 目录下组件, 使用 Vue3 组合式 API 写法

web/src/materials/questions/widgets/BaseChoice/index.jsx
=> fix: 修复物料题型通用组件 BaseChoice 单选类型题重复触发 change 事件问题

web/src/management/pages/create/CreatePage.vue, web/src/management/pages/create/components/CreateForm.vue, web/src/management/pages/create/components/NavHeader.vue, web/src/management/pages/create/components/TypeList.vue
Vue3 组合式 API 写法重构以下组件
management/pages/create/components/CreateForm.vue
management/pages/create/components/NavHeader.vue
management/pages/create/components/TypeList.vue
management/pages/create/CreatePage.vue
=> refactor: Vue3 组合式 API 写法重构/management/pages/create下的组件

web/src/management/pages/edit/components/QuestionWrapper.vue
=> feat: 题型处于活动状态时操作侧边栏默认显示

web/src/management/pages/login/LoginPage.vue
=> refactor: 使用vue3组合式API重构登录页代码

web/src/materials/setters/widgets/CheckboxGroup.vue
=> fix: 题型切换 CheckboxGroup 基础设置组件状态监控导致问题

web/src/management/pages/edit/components/QuestionWrapper.vue
=> fix: 修复问卷编辑-活动题型移动选区未移动问题

web/src/management/pages/edit/components/MaterialGroup.vue
=> fix: 修复题型拖拽移动问题

web/src/materials/questions/widgets/BaseRate/index.jsx
=> fix: 修复物料基础组件 BaseRate 重复触发 change 事件问题

web/src/render/pages/EmptyPage.vue
1重构render/pages/EmptyPage.vue文件
=> refactor: 重构vue3组合式API写法

server/src/enums/exceptionCode.ts, server/src/interfaces/survey.ts, server/src/models/whitelistVerify.entity.ts, server/src/modules/auth/auth.module.ts, server/src/modules/auth/services/whitelist.service.ts, server/src/modules/surveyResponse/__test/responseSchema.controller.spec.ts, server/src/modules/surveyResponse/__test/surveyResponse.controller.spec.ts, server/src/modules/surveyResponse/controllers/responseSchema.controller.ts, server/src/modules/surveyResponse/controllers/surveyResponse.controller.ts, server/src/modules/surveyResponse/surveyResponse.module.ts
=> [Feature] 白名单功能服务端

server/src/guards/__test/survey.guard.spec.ts, server/src/modules/auth/__test/user.service.spec.ts, server/src/modules/survey/__test/collaborator.controller.spec.ts, server/src/modules/survey/__test/dataStatistic.controller.spec.ts, server/src/modules/survey/__test/dataStatistic.service.spec.ts, server/src/modules/survey/controllers/collaborator.controller.ts, server/src/modules/survey/controllers/dataStatistic.controller.ts, server/src/modules/survey/dto/aggregationStatis.dto.ts, server/src/modules/survey/dto/batchSaveCollaborator.dto.ts, server/src/modules/survey/services/dataStatistic.service.ts, server/src/modules/survey/utils/index.ts
=> feat: 新增分题统计接口

web/src/render/index.html, web/src/render/pages/RenderPage.vue
=> feat: 移动端预览优化

web/src/management/hooks/useQuestionInfo.js, web/src/management/hooks/useResizeObserver.js, web/src/management/pages/analysis/components/StatisticsItem.vue, web/src/management/pages/edit/components/MaterialGroup.vue, web/src/management/pages/edit/components/ModuleNavbar.vue, web/src/management/pages/edit/index.vue, web/src/management/pages/edit/modules/contentModule/HistoryPanel.vue, web/src/management/pages/edit/modules/contentModule/PublishPanel.vue, web/src/management/pages/edit/modules/contentModule/SavePanel.vue, web/src/management/pages/edit/modules/questionModule/PreviewPanel.vue, web/src/management/pages/edit/modules/questionModule/SetterPanel.vue, web/src/management/pages/edit/modules/questionModule/components/QuestionCatalog.vue, web/src/management/pages/edit/modules/questionModule/components/TypeList.vue, web/src/management/pages/edit/modules/settingModule/SettingPanel.vue, web/src/management/pages/edit/modules/settingModule/result/CatalogPanel.vue, web/src/management/pages/edit/modules/settingModule/result/PreviewPanel.vue, web/src/management/pages/edit/modules/settingModule/result/SetterPanel.vue, web/src/management/pages/edit/modules/settingModule/skin/CatalogPanel.vue, web/src/management/pages/edit/modules/settingModule/skin/PreviewPanel.vue, web/src/management/pages/edit/modules/settingModule/skin/SetterPanel.vue, web/src/management/pages/edit/pages/edit/LogicEditPage.vue, web/src/management/pages/publish/PublishPage.vue, web/src/management/stores/edit.js, web/src/management/stores/edit.ts, web/vite.config.ts
=> feat: edit vuex迁移pinia

web/src/management/hooks/useCharts.js
=> feat: echarts按需引入

web/src/management/pages/list/index.vue
=> feat(小功能建设): 15团队空间问卷列表页优化

web/src/management/pages/edit/modules/questionModule/CatalogPanel.vue, web/src/management/pages/list/components/SpaceList.vue, web/src/management/pages/list/index.vue
=> 问卷编辑页面题型选择tab、团队空间列表按钮优化

web/src/common/Editor/RichEditor.vue, web/src/materials/questions/widgets/EditOptions/Options/OptionEdit.vue, web/src/materials/questions/widgets/TitleModules/EditTitle/index.jsx
1.题目标题编辑自动focus
2.题目选项编辑自动focus第一个选项
=> feat: 功能18优化

web/src/render/components/MainRenderer.vue, web/src/render/components/QuestionWrapper.vue, web/src/render/hooks/useShowInput.js, web/src/render/hooks/useShowOthers.js, web/src/render/hooks/useVoteMap.js, web/src/render/pages/RenderPage.vue, web/src/render/store/actions.js, web/src/render/store/getters.js, web/src/render/store/mutations.js, web/src/render/store/state.js, web/src/render/stores/question.js
答题页相关 vuex迁移pinia
questionData
questionSeq
renderData（computed）
voteMap
=> feat: 答题页相关vuex迁移pinia

server/src/enums/question.ts, server/src/modules/survey/controllers/dataStatistic.controller.ts, server/src/modules/survey/services/dataStatistic.service.ts, server/src/modules/survey/utils/index.ts
=> feat: 题型硬编码优化

web/src/management/pages/edit/modules/settingModule/skin/CatalogPanel.vue, web/src/management/pages/list/components/MemberSelect.vue, web/src/management/router/index.ts, web/src/management/stores/user.ts
=> fix: user模块升级为ts

web/package.json, web/src/management/pages/edit/index.vue, web/src/materials/setters/widgets/ELSwitch.vue
=> fix: 修正颜色不统一

web/src/render/pages/ErrorPage.vue, web/src/render/store/actions.js, web/src/render/stores/errorInfo.js
改动内容
3、错误页相关
errorInfo
以上变量迁移到pinia
https://github.com/didi/xiaoju-survey/issues/308#issuecomment-2232483833
=> feat: errorInfo to pinia

web/src/management/utils/index.js
=> fix: 修复新增同类型题目设置值不变问题

web/src/materials/setters/widgets/CheckBox.vue, web/src/materials/setters/widgets/InputNumber.vue
修复投票题修改后，再次添加投票题，Checkbox和InputNumber设置器不更新问题
=> fix: 修复设置器不更新问题

web/src/management/stores/edit.ts
=> fix：修复提交按钮属性面板显示空白

web/src/management/pages/edit/modules/generalModule/TitlePanel.vue
修复了短标题hover空白处会触发指示框的bug
https://github.com/didi/xiaoju-survey/issues/364
=> fix(Navbar):修复了短标题hover空白处会触发指示框的bug

web/src/materials/questions/widgets/TitleModules/TitleContent/index.jsx
=> feat: 小功能建设(4)

web/src/management/pages/edit/components/MaterialGroup.vue, web/src/management/pages/edit/components/QuestionWrapper.vue
=> fix: 修复题目未聚焦时拖拽按钮失效问题

survey-common/src/main/java/com/xiaojusurvey/engine/common/enums/SurveyPermissionEnum.java, survey-core/src/main/java/com/xiaojusurvey/engine/core/survey/CollaboratorService.java, survey-server/src/main/java/com/xiaojusurvey/engine/controller/CollaboratorController.java, survey-server/src/test/java/com/xiaojusurvey/engine/controller/CollaboratorControllerTest.java
1.新增获取权限列表接口
2.新增 controller 单元测试
=> [Feature]:新增获取权限列表接口及单元测试

server/src/interfaces/survey.ts, server/src/modules/survey/template/surveyTemplate/survey/normal.json, web/src/management/config/questionConfig.js, web/src/management/pages/edit/modules/contentModule/SavePanel.vue, web/src/materials/questions/widgets/BaseChoice/index.jsx, web/src/materials/questions/widgets/CheckboxModule/index.jsx, web/src/materials/questions/widgets/CheckboxModule/meta.js, web/src/materials/questions/widgets/RadioModule/index.jsx, web/src/materials/questions/widgets/RadioModule/meta.js, web/src/materials/setters/widgets/QuotaConfig.vue, web/src/render/components/QuestionWrapper.vue, web/src/render/hooks/useOptionsQuota.js, web/src/render/hooks/useVoteMap.js, web/src/render/pages/RenderPage.vue, web/src/render/store/actions.js, web/src/render/store/mutations.js, web/src/render/store/state.js
1. 字段优化
2. 选项配额的属性面板配置优化
3. 选项限额设置器组件优化:
4. c端选项限额显示优化: 新增选项配额的hooks，使得逻辑更加解耦，不和投票题的逻辑杂糅在一起
=> perl: 选项配额优化

web/src/render/components/VerifyWhiteDialog.vue, web/src/render/pages/RenderPage.vue
=> fix:修复C端白名单验证弹框不出现的问题

web/src/management/pages/edit/components/QuestionWrapper.vue
=> refactor: 题目删除和逻辑关联优化,#182

web/src/management/styles/icon.scss
=> feat: 更新iconfont链接

web/src/management/hooks/useJumpLogicInfo.js, web/src/management/hooks/useShowLogicInfo.js, web/src/management/stores/edit.ts
=> fix: 删除分页判断是否存在题目的逻辑关联

.gitignore, server/.env, server/package.json, server/src/modules/survey/template/surveyTemplate/survey/vote.json, server/src/modules/surveyResponse/controllers/surveyResponse.controller.ts, server/src/utils/xss.ts, web/src/management/pages/edit/components/ModuleNavbar.vue, web/src/management/pages/edit/index.vue, web/src/management/pages/edit/modules/contentModule/SavePanel.vue, web/src/management/pages/edit/modules/generalModule/NavPanel.vue, web/src/management/pages/edit/modules/questionModule/CatalogPanel.vue, web/src/management/pages/edit/modules/questionModule/SetterPanel.vue, web/src/management/pages/edit/modules/questionModule/components/AdvancedConfig/OptionConfig.vue, web/src/management/pages/edit/setterConfig/baseFormConfig.js, web/src/materials/questions/widgets/BaseChoice/style.scss, web/src/materials/questions/widgets/CheckboxModule/index.jsx, web/src/materials/questions/widgets/CheckboxModule/meta.js, web/src/materials/questions/widgets/VoteModule/meta.js, web/src/materials/setters/widgets/CustomedSwitch.vue, web/src/materials/setters/widgets/ELSwitch.vue, web/src/materials/setters/widgets/InputNumber.vue, web/src/materials/setters/widgets/QuotaConfig.vue, web/src/render/components/QuestionWrapper.vue, web/src/render/pages/IndexPage.vue, web/src/render/pages/RenderPage.vue, web/src/render/stores/survey.js
fix: 修复选项引用验收bug
fix: 修复断点续答问题
fix: 修复断点续答
fix: ignore
fix: 修复投票题默认值
fix: 优化断点续答逻辑
fix: 选中图标适应高度
fix: 回退最大最小选择
fix: 修复断点续答
fix: 修复elswitch不更新问题
fix: 修复访问密码更新不生效问题
fix: 修复样式
fix: 修复多选题最大最小限制
fix: 优化断点续答问题
fix: 修复多选题命中最多选择后无法取消问题
fix: 修复服务端的富文本解析
=> fix: 修复断点续答以及样式问题

web/src/management/pages/edit/pages/edit/LogicIndex.vue, web/src/render/stores/question.js
=> fix: 修复显示逻辑列表不能滚动以及c端渲染页报错

web/src/management/pages/edit/pages/edit/index.vue
=> feat: 编辑态优化

server/src/modules/survey/__test/survey.controller.spec.ts, server/src/modules/survey/controllers/dataStatistic.controller.ts, server/src/modules/survey/controllers/survey.controller.ts, web/src/management/pages/analysis/components/DataTable.vue, web/src/management/pages/edit/modules/contentModule/PublishPanel.vue, web/src/management/pages/edit/modules/questionModule/components/AdvancedConfig/OptionConfig.vue, web/src/render/components/MainRenderer.vue, web/src/render/components/QuestionWrapper.vue, web/src/render/stores/question.js
1. 题目被逻辑配置隐藏时跳过分页
2. 题目编辑后直接点击发布，没生效
3. 修复投票题B端设置了选项输入框，C端不生效
4. 修复没有题目时提交报错
5. 修复数据表格的标题富文本没清空
6. 分题统计接口做接口鉴权
7. 修复数据表格tooltip错位
=> [Fix]：缺陷修复回流

web/src/management/pages/edit/modules/contentModule/SavePanel.vue
1. 问卷编辑保存优化
https://github.com/didi/xiaoju-survey/issues/182#issuecomment-2636178191
=> [Refactor]: 自动保存优化

web/src/management/pages/edit/components/ModuleNavbar.vue, web/src/management/pages/edit/pages/edit/LogicIndex.vue
1. 优化逻辑编排检测
https://github.com/didi/xiaoju-survey/issues/182
=> [Refactor]: 优化逻辑编排检测
