web/src/management/api/survey.js
web/src/management/pages/list/components/baseList.vue
web/src/management/pages/list/components/textButton.vue
web/src/management/pages/list/config/index.js

[Feature]: 问卷列表新增排序功能

---

web/src/materials/questions/widgets/NpsModule/index.vue
web/src/materials/questions/widgets/StarModule/index.jsx

1. 1.0分和1分均有更多输入框，0分的输入框必填、1分的输入框非必填，0分+输入框为空的情况会正常校验和提示，此时选择1分，输入框还是会有校验提示（提示应该消失）
2.评分题同理

fix: 修复评分和nps题型非必填提示没有填写的问题

---

Dockerfile
docker-compose.yaml
docker-run.sh
nginx/nginx.conf

1.更改Dockerfile文件
加入安装nginx 命令RUN apt-get update && \ apt-get install -y nginx
加入覆盖nginx配置文件的命令COPY ./nginx/nginx.conf /etc/nginx/nginx.conf
更改暴露的端口号由后端服务的3000端口更改为nginx的8080端口
2.更改docker-run.sh 文件加入启动nginx的命令 nginx -g 'daemon on;'
3.修改docker-compose.yaml 文件将项目将暴露的"8080:3000" 更改为 "8080:8080"
4.在项目根目录新建了一个nginx的文件夹里面创建nginx.conf 用于覆盖默认的nginx配置

fix:前端项目使用nginx服务代理,不在使用后端服务代理

---

web/src/render/pages/ErrorPage.vue
web/src/render/pages/IndexPage.vue
web/src/render/pages/SuccessPage.vue

使用 Vue3 组合式 API 写法, 重构下例三个文件
render/pages/ErrorPage.vue
render/pages/IndexPage.vue
render/pages/SuccessPage.vue

[Refactor]: 重构 render/pages 目录下三个文件, 使用 Vue3 组合式 API 写法

---

web/src/render/App.vue
web/src/render/main.js

refactor: 重构 render/App.vue, 使用 Vue3 组合式 API 写法

---

web/src/management/pages/edit/components/QuestionWrapper.vue

修复问卷编辑页最后一题处于活动状态下删除导致问题
改动文件：
```bash
src/management/pages/edit/components/QuestionWrapper.vue
```
[最后一题活动状态下删除操作会触发两处问题](https://github.com/didi/xiaoju-survey/issues/140)

fix: 修复问卷编辑页最后一题处于活动状态下删除导致问题

---

web/src/render/components/AlertDialog.vue
web/src/render/components/ConfirmDialog.vue
web/src/render/components/HeaderSetter.vue
web/src/render/components/LogoIcon.vue
web/src/render/components/MainRenderer.vue
web/src/render/components/MainTitle.vue
web/src/render/components/SubmitSetter.vue
web/src/render/styles/icon.scss

下列组件, 调整成 Vue3 组合式 API 写法
```bash
render
├── components                                                
│   ├── AlertDialog.vue
│   ├── ConfirmDialog.vue
│   ├── HeaderSetter.vue
│   ├── LogoIcon.vue
│   ├── MainRenderer.vue
│   ├── MainTitle.vue
│   ├── SubmitSetter.vue
```

refactor: 重构 render/components 目录下部分组件, 使用 Vue3 组合式 API 写法

---

web/src/materials/setters/widgets/CheckBox.vue
web/src/materials/setters/widgets/CheckboxGroup.vue
web/src/materials/setters/widgets/ColorInput.vue
web/src/materials/setters/widgets/ColorPicker.vue
web/src/materials/setters/widgets/FormItem.vue
web/src/materials/setters/widgets/FormdataBackFill.vue
web/src/materials/setters/widgets/FreqAndNumberLimit.vue
web/src/materials/setters/widgets/InputNumber.vue
web/src/materials/setters/widgets/InputPercent.vue
web/src/materials/setters/widgets/InputSetter.vue
web/src/materials/setters/widgets/MultiInput.vue
web/src/materials/setters/widgets/MultiSelect.vue
web/src/materials/setters/widgets/QuestionTime.vue
web/src/materials/setters/widgets/QuestionTimeHour.vue
web/src/materials/setters/widgets/RadioGroup.vue
web/src/materials/setters/widgets/RadioSetter.vue
web/src/materials/setters/widgets/RangeSetter.vue
web/src/materials/setters/widgets/RichText.vue
web/src/materials/setters/widgets/SelectSetter.vue
web/src/materials/setters/widgets/SliderSetter.vue

下列组件, 调整成 Vue3 组合式 API 写法
materials
│── setters
│   └── widgets
│       ├── CheckBox.vue
│       ├── CheckboxGroup.vue
│       ├── ColorInput.vue
│       ├── ColorPicker.vue
│       ├── FormItem.vue
│       ├── FormdataBackFill.vue
│       ├── FreqAndNumberLimit.vue
│       ├── InputNumber.vue
│       ├── InputPercent.vue
│       ├── InputSetter.vue
│       ├── MultiInput.vue
│       ├── MultiSelect.vue
│       ├── QuestionTime.vue
│       ├── QuestionTimeHour.vue
│       ├── RadioGroup.vue
│       ├── RadioSetter.vue
│       ├── RangeSetter.vue
│       ├── RichText.vue
│       ├── SelectSetter.vue
│       └── SliderSetter.vue

refactor: 重构 materials/setters/widgets 目录下部分组件, 使用 Vue3 组合式 API 写法

---

web/src/management/pages/edit/components/MaterialGroup.vue
web/src/management/pages/edit/components/QuestionWrapper.vue

QuestionWrapper.vue 组件
``` ts
const clickFormItem = () => {
const index = props.qIndex
if (!props.isSelected) {  // 此处增加代码
emit('select', index)
}
}
```
#154

fix: 修复活动题型选区多次点击重复触发 select 事件 (#154)

---

web/package.json
web/src/management/components/LeftMenu.vue
web/src/management/pages/edit/modules/contentModule/PublishPanel.vue
web/src/management/pages/list/components/ToolBar.vue
web/src/management/pages/publish/PublishPage.vue
web/src/management/pages/publish/components/ChannelRow.vue
web/src/management/pages/publish/components/QRCode.vue
web/src/management/router/index.ts

使用 Vue3 组合式 API 写法对 management/pages/publishResult 目录列表文件进行调整
```bash
management/pages/publishResult
├── PublishResultPage.vue
└── components
├── ChannelRow.vue
└── QRCode.vue
```

refactor: 重构 management/pages/publishResult 目录下组件, 使用 Vue3 组合式 API 写法

---

web/src/materials/setters/widgets/RangeSetter.vue

fix: 修复物料设置组件 RangeSetter 在设置最大值与最小值引发问题

---

web/src/management/pages/edit/components/ModuleNavbar.vue
web/src/management/pages/edit/components/SetterField.vue
web/src/management/pages/edit/index.vue
web/src/management/pages/edit/modules/contentModule/HistoryPanel.vue
web/src/management/pages/edit/modules/contentModule/PublishPanel.vue
web/src/management/pages/edit/modules/contentModule/SavePanel.vue
web/src/management/pages/edit/modules/generalModule/BackPanel.vue
web/src/management/pages/edit/modules/generalModule/NavPanel.vue
web/src/management/pages/edit/modules/generalModule/TitlePanel.vue
web/src/management/pages/edit/modules/questionModule/CatalogPanel.vue
web/src/management/pages/edit/modules/questionModule/SetterPanel.vue
web/src/management/pages/edit/modules/questionModule/components/CatalogItem.vue
web/src/management/pages/edit/modules/questionModule/components/QuestionCatalog.vue
web/src/management/pages/edit/modules/settingModule/SettingPanel.vue
web/src/management/pages/edit/modules/settingModule/components/OverTime.vue
web/src/management/pages/edit/modules/settingModule/components/SuccessContent.vue
web/src/management/pages/edit/modules/settingModule/result/CatalogPanel.vue
web/src/management/pages/edit/modules/settingModule/result/PreviewPanel.vue
web/src/management/pages/edit/modules/settingModule/result/SetterPanel.vue
web/src/management/pages/edit/modules/settingModule/skin/CatalogPanel.vue
web/src/management/pages/edit/modules/settingModule/skin/SetterPanel.vue
web/src/management/pages/edit/pages/edit/LogicEditPage.vue
web/src/management/pages/edit/pages/edit/QuestionEditPage.vue
web/src/management/pages/edit/pages/edit/index.vue
web/src/management/pages/edit/pages/setting/index.vue
web/src/management/pages/edit/pages/skin/ContentPage.vue
web/src/management/pages/edit/pages/skin/ResultPage.vue
web/src/management/pages/edit/pages/skin/index.vue

使用 Vue3 组合式 API 写法对 management/pages/edit 目录列表文件进行调整
```bash
src/management/pages/edit
├── components
│   ├── LogoPreview.vue
│   ├── MainTitle.vue
│   ├── ModuleNavbar.vue
│   ├── SetterField.vue
│   └── SubmitButton.vue
├── index.vue
├── modules
│   ├── contentModule
│   │   ├── HistoryPanel.vue
│   │   ├── PublishPanel.vue
│   │   └── SavePanel.vue
│   ├── generalModule
│   │   ├── BackPanel.vue
│   │   ├── NavPanel.vue
│   │   └── TitlePanel.vue
│   ├── questionModule
│   │   ├── CatalogPanel.vue
│   │   ├── SetterPanel.vue
│   │   └── components
│   │       ├── CatalogItem.vue
│   │       └── QuestionCatalog.vue
│   └── settingModule
│       ├── SettingPanel.vue
│       ├── components
│       │   ├── BannerContent.vue
│       │   ├── OverTime.vue
│       │   └── SuccessContent.vue …
```

refactor: 重构 management/pages/edit 目录下组件, 使用 Vue3 组合式 API 写法

---

survey-dal/src/main/java/com/xiaojusurvey/engine/repository/MongoRepository.java
survey-dal/src/main/java/com/xiaojusurvey/engine/repository/impl/MongoRepositoryImpl.java

改动原因
基于springdata 对MongoRepository通用封装（基础）。
改动内容
1、增加 CRUD 操作；
2、增加 count、exists、aggregate 操作；
3、增加多条件分页查询；
改动验证
使用本地的 mongodb 服务器已验证操作的正确性。

[Feature] 增加 mongo repository 的 CRUD、聚合、分页等基础实现

---

web/src/management/api/space.ts
web/src/management/components/LeftMenu.vue
web/src/management/pages/edit/modules/generalModule/BackPanel.vue
web/src/management/pages/list/components/SpaceList.vue
web/src/management/router/index.ts
web/src/management/store/actions.js
web/src/materials/questions/widgets/EditOptions/Options/OptionEditBar.vue
web/src/render/components/MaterialGroup.vue
web/src/render/components/QuestionWrapper.vue
web/src/render/pages/IndexPage.vue
web/src/render/store/getters.js

1. 编辑页左侧的菜单监听权限数据，填充相应权限的菜单，避免编辑页重复发起权限请求
2. 导航守卫的权限接口先判断跳转时是否是编辑页再判断跳转的编辑页的id是否改变来请求接口，避免每次路由改变发起权限请求
3. 优化返回按钮的路由跳转方式
4. 去掉使用不到的attrs透传
5. 去掉部分console.log

feat: 权限接口请求优化以及修复其他问题

---

web/src/management/pages/edit/modules/logicModule/components/ConditionView.vue
web/src/management/pages/edit/modules/logicModule/components/RuleNodeView.vue
web/src/render/App.vue
web/src/render/main.js
web/src/render/pages/ErrorPage.vue
web/src/render/pages/IndexPage.vue
web/src/render/pages/RenderPage.vue
web/src/render/router/index.ts
web/src/render/store/actions.js
web/src/render/store/mutations.js
web/src/render/store/state.js

1. 新增router表
2. main引入router
3. app.vue中异步组件改为
4. 异步组件切换改为路由跳转，commit('setRouter', 'errorPage')，改为router.push({ name: 'errorPage'})形式
5. 新增一个公共页面：renderPage，
6. 统一errorpage页面的dom结构样式和successPage保持一致
7. 兼容预览的改动

feat: c端路由改造

---

server/src/modules/survey/template/surveyTemplate/survey/normal.json
server/src/modules/survey/template/surveyTemplate/survey/nps.json
server/src/modules/survey/template/surveyTemplate/survey/register.json
server/src/modules/survey/template/surveyTemplate/survey/vote.json
server/src/modules/survey/utils/index.ts
web/src/management/pages/edit/components/SetterField.vue
web/src/management/pages/list/components/MemberList.vue
web/src/management/pages/list/components/MemberSelect.vue
web/src/management/utils/index.js
web/src/materials/questions/common/config/basicConfig.js
web/src/materials/questions/widgets/BinaryChoiceModule/meta.js
web/src/materials/questions/widgets/CheckboxModule/meta.js
web/src/materials/questions/widgets/EditOptions/Options/OptionEdit.vue
web/src/materials/questions/widgets/InputModule/meta.js
web/src/materials/questions/widgets/NpsModule/index.jsx
web/src/materials/questions/widgets/NpsModule/meta.js
web/src/materials/questions/widgets/NpsModule/style.scss
web/src/materials/questions/widgets/RadioModule/meta.js
web/src/materials/questions/widgets/StarModule/meta.js
web/src/materials/questions/widgets/TextareaModule/meta.js
web/src/materials/questions/widgets/VoteModule/meta.js
web/src/materials/setters/widgets/InputNumber.vue
web/src/materials/setters/widgets/RangeSetter.vue
web/src/materials/setters/widgets/SelectSetter.vue
web/src/render/adapter/formValue.js
web/src/render/adapter/question.js
web/src/render/adapter/rules.js
web/src/render/components/QuestionWrapper.vue
web/src/render/store/actions.js

解决题型数据泥团整个存储在配置中，预期能就达到输入题只存储输入题相关字段，选择题只存储选择题的相关字段，即题型字段根据题型做过滤
1. meta增加attrs字段作为题型属性信息描述
2. 添加题目时，获取对应题型的meta中的题型属性信息生成对应题型的默认字段
3. 后端修改问卷题目模版根据题型返回固定字段
4. 减少题型判断以及必要的判空兼容
schema分离的其他优化改动点：
1. valueAdapter调整为valueGetter，和文档保持一致
2. setterAdapter调整为valueSetter
5. 去掉多余字段，cleanKeys没有用到
6. 修复nps题的量表设置不生效, 新增validate配置
7. 修复vue的警告：withDefaults 不需要import 
8. 修复nps题的填写更多不生效
9. 修复render在结果页刷新没有跳转到答题页

feat: schema分离

---

web/src/materials/questions/QuestionContainerB/index.jsx
web/src/materials/questions/widgets/EditOptions/AdvancedConfig/RateConfig.vue
web/src/materials/questions/widgets/EditOptions/Options/OptionEdit.vue
web/src/materials/questions/widgets/EditOptions/index.jsx

1. 调整组件传参，从搭建端传递chage事件
2. 编辑态的设置触发搭建端传递的change事件，不直接在物料的编辑态触发store的changeSchema方法

feat: 物料脱离store依赖

---

web/src/management/hooks/useResizeObserver.js
web/src/management/pages/analysis/components/StatisticsItem.vue

数据统计 - 分题统计
修复引入 import lodash cloneDeep debounce 错误 改为 lodash-es 了。
早在三个月前 `lodash` 依赖就改成了 [fix: 升级lodash-es](https://github.com/didi/xiaoju-survey/pull/73)
分题统计代码是6月21新增的。
>[2024-06-21 16:33 +0800 hiStephen I feat: 分题统计前端开发 (#276)](https://github.com/didi/xiaoju-survey/pull/276)
可能开发时没有重新安装更新依赖，或者用的 `npm`，有幽灵依赖。所以本地开发没有报错。

fix: 🐛 修复引入 import lodash cloneDeep debounce 错误 改为 lodash-es 了

---

survey-server/src/main/resources/application-dev.properties

1. 修复 dev 配置文件中 MongoDB 相关的 `spring.data.mongodb.uri` 配置项为空导致覆盖掉已配置好的 `host`, `port`, `database` 等配置从而出现启动失败的问题

[Fix]: 修复 dev 配置文件中 MongoDB 重复配置项导致的启动失败问题

---

web/src/render/pages/IndexPage.vue
web/src/render/pages/RenderPage.vue
web/src/render/store/actions.js
web/src/render/store/mutations.js
web/src/render/store/state.js
web/src/render/stores/survey.js

1、问卷相关
surveyPath
isMobile
enterTime
encryptInfo
以上变量迁移到pinia
https://github.com/didi/xiaoju-survey/issues/308#issuecomment-2199219412

feat: survey vuex to pinia

---

survey-common/src/main/java/com/xiaojusurvey/engine/common/constants/RespErrorCode.java
survey-core/src/main/java/com/xiaojusurvey/engine/core/auth/impl/AuthServiceImpl.java
survey-core/src/main/java/com/xiaojusurvey/engine/core/auth/util/AuthUtil.java
survey-core/src/main/java/com/xiaojusurvey/engine/core/auth/util/JwtTokenUtil.java
survey-core/src/main/java/com/xiaojusurvey/engine/core/user/UserService.java
survey-core/src/main/java/com/xiaojusurvey/engine/core/user/impl/UserServiceImpl.java
survey-server/src/main/java/com/xiaojusurvey/engine/interceptor/LoginInterceptor.java

改动原因：
1.  java端接口注册的用户没法在node端登录
2. jwt存储了用户password关键信息
3. 方便java版本开发的同学做接口验证调试
改动内容：
1. 去除jwt存储password关键信息；token创建逻辑同node，jwt信息实现node和java互通
2. 新增hash256方法，用户注册password加密逻辑同node,实现java端注册的账号登录和node版本互通
改动验证：
1. 调用java注册用户，在mian分支下node服务正常登录，且node服务注册的用户在java版本的登录接口正常登陆
2. node服务下的token在java端可以正常获取到用户信息

处理java端用户体系和node逻辑保持一致

---

survey-core/src/main/java/com/xiaojusurvey/engine/core/auth/impl/AuthServiceImpl.java

[Fix]: 修复生成的 token 缺失 id导致登录校验出错

---

web/src/management/pages/edit/modules/questionModule/SetterPanel.vue
web/src/management/stores/composables/useEditGlobalBaseConf.ts
web/src/management/stores/edit.ts

1. 在问卷配置模块增加整卷配置功能UI
2. 在stores/edit 增加 整卷逻辑组合函数
3. 在初始化问卷，修改问卷更新整卷配置状态(通过问卷长度和每个问卷选中的个数对比计算整卷各项状态)
4. 监听整卷选择更新问卷数据到服务器

feat: 整卷增加基础配置：必填、显示类型、显示序号、显示分割线

---

web/src/common/logicEngine/RuleBuild.ts
web/src/common/logicEngine/RulesMatch.ts
web/src/management/hooks/useJumpLogicInfo.js
web/src/management/hooks/useShowLogicInfo.js
web/src/management/pages/edit/components/QuestionWrapper.vue
web/src/render/adapter/index.js
web/src/render/adapter/question.js
web/src/render/components/MaterialGroup.vue
web/src/render/components/QuestionWrapper.vue
web/src/render/stores/question.js
web/src/render/stores/survey.js
web/src/render/utils/index.js

跳转逻辑方案优化
1. 构建一个全局NeedHideFields变量，条件题变化时，
- 未命中的目标数据 --> 题目展示：根据条件题和未匹配的目标题，找到需要被展示的题，调用removeNeedHideMap
- 命中目标题数组 --> 题目隐藏：根据条件题和匹配的目标题，找到需要被隐藏的题，调用addNeedHideMap，注意，已经被隐藏的题不需要重复插入
2. 题目组件渲染时，拿field和NeedHideFields比对，如果存在则不显示题目
其他优化：
1. ruleMatch新增getResultsByField函数根据条件题id获取所有关联的目标题匹配情况
2. 放弃使用监听formValues方案，抽离processJumpSkip函数，在题目change时调用
3. 如果配置了跳转逻辑的题目被隐藏了则清空该题的值
4. 优化getQuestionIndexByField，从Map结构中获取index，避免数组遍历

fix: 跳转逻辑优化

---

web/package.json
web/src/management/pages/edit/modules/questionModule/CatalogPanel.vue
web/src/management/pages/edit/modules/questionModule/SetterPanel.vue
web/src/materials/questions/widgets/EditOptions/Options/OptionEditBar.vue

问题表现：![image](https://github.com/user-attachments/assets/d789809a-0ff9-4d0f-bd7e-03370980d6e9)
根因：最新element-plust调整了tab组件的结构和样式，同时业务组件自定义flex-direction: column;导致tab表现异常
解决方案：声明element-plus的最小版本为2.8.1，去掉自定义的样式flex-direction: column;

fix：修复编辑页在不同element版本下表现不一致问题

---

web/src/materials/questions/widgets/TitleModules/TitleContent/index.jsx

1. 修正前端题目TitleModule组件点击工具条上传图片触发关闭title编辑的bug

fix: 修复富文本编辑器上传图片

---

web/src/management/pages/edit/modules/contentModule/SavePanel.vue

1. 将自动保存成功的提示修改为与“保存中”相同的样式
2. 调整了保存问卷的方法结构，确保自动保存与手动保存的逻辑一致

feat:自动保存优化

---

web/src/management/pages/edit/modules/questionModule/components/TypeList.vue
web/src/management/stores/edit.ts

未选中任何题目的前提下，点击左侧题型或者拖动题目到中间画布时，需要选中当前新增的题目
https://github.com/didi/xiaoju-survey/issues/182

feat: 新增题目优化

---

server/src/modules/survey/controllers/surveyGroup.controller.ts
server/src/modules/survey/services/surveyMeta.service.ts
web/src/management/pages/list/components/ModifyDialog.vue
web/src/management/pages/list/components/SliderBar.vue
web/src/management/pages/list/index.vue
web/src/management/stores/surveyList.ts
web/src/management/styles/common.scss
web/src/management/utils/workSpace.ts

fix: 修复问卷分组bug

---

survey-core/src/main/java/com/xiaojusurvey/engine/core/survey/SurveyResponseService.java
survey-core/src/main/java/com/xiaojusurvey/engine/core/survey/impl/SurveyResponseServiceImpl.java
survey-core/src/main/java/com/xiaojusurvey/engine/core/survey/vo/SurveyResponseSchemaOutVO.java
survey-server/src/main/java/com/xiaojusurvey/engine/controller/SurveyResponseController.java
survey-server/src/test/java/com/xiaojusurvey/engine/controller/SurveyResponseControllerTest.java

[Feat]:  实现C端接口，获取已发布问卷的schema

---

web/src/materials/setters/widgets/CheckBox.vue
web/src/materials/setters/widgets/SelectSetter.vue

1. 去掉多选题设置器中的题目字段
2. 去掉下拉框设置器中的题目字段

fix: 去除设置器中不存在的题目字段

---

server/src/modules/survey/__test/survey.controller.spec.ts
server/src/modules/survey/controllers/dataStatistic.controller.ts
server/src/modules/survey/controllers/survey.controller.ts
web/src/management/pages/analysis/components/DataTable.vue
web/src/management/pages/edit/modules/contentModule/PublishPanel.vue
web/src/management/pages/edit/modules/questionModule/components/AdvancedConfig/OptionConfig.vue
web/src/render/components/MainRenderer.vue
web/src/render/components/QuestionWrapper.vue
web/src/render/stores/question.js

1. 题目被逻辑配置隐藏时跳过分页
2. 题目编辑后直接点击发布，没生效
3. 修复投票题B端设置了选项输入框，C端不生效
4. 修复没有题目时提交报错 
5. 修复数据表格的标题富文本没清空
6. 分题统计接口做接口鉴权
7. 修复数据表格tooltip错位

fix: 缺陷修复回流

---

web/src/management/pages/edit/components/Picker/event.ts
web/src/management/pages/edit/components/Picker/index.vue

[Fix]: 解决getCurrentInstance()在开发环境和生产环境拿到的值不一样

---

server/src/enums/exceptionCode.ts
server/src/models/surveyMeta.entity.ts
server/src/modules/survey/__test/collaborator.service.spec.ts
server/src/modules/survey/controllers/recycleBin.controller.ts
server/src/modules/survey/controllers/surveyMeta.controller.ts
server/src/modules/workspace/_test/workspace.service.spec.ts
web/src/management/pages/list/components/RecycleBinList.vue
web/src/management/pages/list/index.vue
web/src/management/stores/workSpace.ts

1. 字段命名不一致和拼写错误
2. 菜单项更新逻辑脆弱
3. 测试数据未模拟依赖
4. 前端状态管理优化
5. 接口参数传递问题
6. 删除操作提示优化

fix: 修复回收站验收问题
